### ISSUE TITLE
Hi what system linux is? thank

### ISSUE THREAD

**Issue by osintyes** [AnarchoTechNYC/ansible-role-onionshare#1]
![68747470733a2f2f7765622e617263686976652e6f72672f7765622f32303137303231393231313130382f68747470733a2f2f692e696d6775722e636f6d2f64494261625a662e6a7067](https://user-images.githubusercontent.com/52049434/59954314-e99d7280-9438-11e9-9cc2-aa0f596e601e.jpg)

**Comment by fabacab** [comment]
Um.

**Comment by osintyes** [comment]
??????
